### ISSUE TITLE
Create a grouped navigation

### ISSUE THREAD

**Issue by jlooper** [FrontEndFoxes/kitchen-sune#40]
As our recipe book grows, we should group the recipes by tag, maybe by breakfast/lunch/dinner/snack with an expandable tree structure

**Comment by OmoBolarinwaye** [comment]
Good evening, can i get guidance on how to fix this?

**Comment by jlooper** [comment]
> Good evening, can i get guidance on how to fix this?

hi @OmoBolarinwaye - we'd have to read through the VuePress docs. It's probably a manual fix to config.js
